inputs_def:
  - handle: ffmpeg_source
    description: Input
    json_schema:
      contentMediaType: oomol/var
    value: ""
  - handle: file_name
    json_schema:
      type: string
  - handle: formate
    json_schema:
      type: string
      enum:
        - mp4
        - mp3
        - aac
        - wav
        - flac
        - wma
        - m4a
      ui:options:
        labels:
          - MP4
          - MP3
          - AAC
          - " WAV"
          - FLAC
          - WMA
          - M4A
  - handle: save_address
    json_schema:
      type: string
      minLength: 1
      ui:widget: dir
    value:
    nullable: true
outputs_def:
  - handle: file_adress
    description: Output
    json_schema:
      type: string
      minLength: 1
      ui:widget: file
icon: ":fa6-solid:floppy-disk:currentColor:"
ui:
  default_width: 447.06350824621484
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
